window.cfaReviewLevels = [
  {
    id: "1",
    label: "Level I",
    labelZh: "一级 · 基础理解",
    focus: "Learn and describe · 认识术语、概念与基础公式",
    topics: [
      { category: "Ethical and Professional Standards", categoryZh: "道德与专业准则", weight: "10–15%", title: "Material nonpublic information", titleZh: "重大非公开信息", explanation: "Do not trade or cause others to trade on information that is both material and not public. Mosaic theory permits conclusions built from public information plus nonmaterial nonpublic details.", explanationZh: "如果信息既重大又未公开，就不能据此交易或让别人交易。公开资料加上不重大的非公开细节，可以通过“马赛克理论”形成投资判断。", exampleZh: "例：朋友私下说公司明天会被收购，这会明显影响股价且尚未公开，因此不能先买股票。", formula: "Material + nonpublic → do not trade" },
      { category: "Quantitative Methods", categoryZh: "数量方法", weight: "11–14%", title: "Time value of money", titleZh: "货币时间价值", explanation: "Money today can earn a return, so it is worth more than the same amount received later. Discount future cash flows to compare values at one date.", explanationZh: "今天的钱可以产生收益，所以比未来同额的钱更值钱。把未来现金流折现回同一日期，才能公平比较。", exampleZh: "例：一年后收到 105 元，若市场利率为 5%，今天的价值就是 105 ÷ 1.05 = 100 元。", formula: "PV = FV / (1 + r)ⁿ" },
      { category: "Economics", categoryZh: "经济学", weight: "6–9%", title: "Supply, demand, and equilibrium", titleZh: "供给、需求与均衡", explanation: "A market equilibrium occurs where quantity supplied equals quantity demanded. A demand increase generally raises equilibrium price and quantity, all else equal.", explanationZh: "供给量等于需求量的位置就是市场均衡。在其他条件不变时，需求增加通常会同时推高均衡价格和成交数量。", exampleZh: "例：炎热天气令更多人买冰淇淋，需求曲线右移；若供应暂时不变，价格通常上涨。", formula: "Equilibrium: Qd = Qs" },
      { category: "Financial Statement Analysis", categoryZh: "财务报表分析", weight: "11–14%", title: "Connect the three statements", titleZh: "连接三张财务报表", explanation: "Net income flows into retained earnings and starts the cash-flow statement. Noncash charges are adjusted, and ending cash must reconcile to cash on the balance sheet.", explanationZh: "净利润会进入留存收益，也是现金流量表的起点；非现金项目需要调整，期末现金必须与资产负债表上的现金一致。", exampleZh: "例：公司赚 20 元但有 5 元折旧。折旧减少利润却没有付现金，所以经营现金流会把这 5 元加回来。", formula: "Ending cash = beginning cash + CFO + CFI + CFF" },
      { category: "Corporate Finance", categoryZh: "公司金融", weight: "6–9%", title: "Net present value", titleZh: "净现值 NPV", explanation: "NPV compares the present value of project cash inflows with the initial investment. A positive NPV project adds value when cash flows and the discount rate are estimated appropriately.", explanationZh: "NPV 比较项目未来现金流的现值与初始投入。若现金流和折现率估计合理，NPV 为正代表项目能增加价值。", exampleZh: "例：今天投入 100 元，一年后收回 112 元；要求回报率 10% 时，NPV = 112/1.10 − 100 = 1.82 元。", formula: "NPV = Σ CFₜ/(1+r)ᵗ − initial investment" },
      { category: "Equities", categoryZh: "权益投资", weight: "11–14%", title: "Dividend discount model", titleZh: "股利折现模型", explanation: "A share is worth the present value of expected future dividends. For stable perpetual growth, value depends on next year's dividend, required return, and growth.", explanationZh: "股票价值可以看作未来预期股利的现值。若股利永续稳定增长，价值取决于下一年股利、要求回报率和增长率。", exampleZh: "例：明年股利 5 元、要求回报 10%、长期增长 4%，股票估值为 5 ÷ (10%−4%) = 83.33 元。", formula: "V₀ = D₁ / (r − g)" },
      { category: "Fixed Income", categoryZh: "固定收益", weight: "11–14%", title: "Bond price and yield", titleZh: "债券价格与收益率", explanation: "A bond's price is the present value of coupons and principal. When the required yield rises, those fixed cash flows are discounted more heavily and price falls.", explanationZh: "债券价格等于票息和本金的现值。要求收益率上升时，固定现金流会用更高利率折现，因此债券价格下降。", exampleZh: "例：旧债券每年只付 3 元，而新债券能付 5 元，投资者只愿意打折购买旧债券。", formula: "Yield ↑ → bond price ↓" },
      { category: "Derivatives and Risk Management", categoryZh: "衍生品与风险管理", weight: "6–9%", title: "Forward commitment versus option", titleZh: "远期承诺与期权选择权", explanation: "A forward obligates both sides to transact later at an agreed price. An option gives its buyer a right without an obligation, in exchange for paying premium.", explanationZh: "远期要求双方未来按约定价格交易；期权买方支付期权费，获得权利但没有必须行权的义务。", exampleZh: "例：远期像签约下月必须用 100 元买玩具；期权像付 5 元订金，下月可决定是否用 100 元买。", formula: "Forward = obligation | Option = right" },
      { category: "Alternative Investments", categoryZh: "另类投资", weight: "6–9%", title: "Illiquidity and diversification", titleZh: "低流动性与分散化", explanation: "Private equity, real estate, infrastructure, commodities, and hedge funds may diversify traditional portfolios, but often add illiquidity, complex fees, and valuation uncertainty.", explanationZh: "私募股权、房地产、基础设施、商品和对冲基金可能帮助分散传统组合，但往往也带来低流动性、复杂费用和估值不确定性。", exampleZh: "例：房子价格未必和股票每天同涨同跌，但卖房通常要几个月，不能像股票一样立即变现。", formula: "Diversification benefit depends on correlation, not labels" },
      { category: "Portfolio Construction", categoryZh: "投资组合构建", weight: "8–12%", title: "Diversification reduces specific risk", titleZh: "分散化降低非系统风险", explanation: "Combining imperfectly correlated assets can reduce company-specific risk. Market-wide systematic risk remains and is rewarded through expected return.", explanationZh: "把相关性不完全一致的资产组合起来，可以降低公司特有风险；整个市场共同面对的系统性风险仍然存在。", exampleZh: "例：只开一家冰淇淋店很怕雨天；同时经营雨伞店后，一个生意差时另一个可能变好。", formula: "Portfolio risk depends on weights, volatility, and correlation" }
    ]
  },
  {
    id: "2",
    label: "Level II",
    labelZh: "二级 · 分析估值",
    focus: "Analyze and evaluate · 在案例中分析、估值与判断",
    topics: [
      { category: "Ethical and Professional Standards", categoryZh: "道德与专业准则", weight: "10–15%", title: "Research objectivity and soft dollars", titleZh: "研究独立性与软佣金", explanation: "Brokerage paid with client assets must benefit the client. Gifts, issuer-paid travel, and compensation arrangements must not compromise independent judgment.", explanationZh: "用客户资产支付的交易佣金必须让客户受益。礼物、发行人支付的差旅或报酬安排都不能损害独立判断。", exampleZh: "例：基金经理不能因为券商送豪华旅行，就把客户交易交给执行质量较差的券商。", formula: "Client brokerage → client benefit" },
      { category: "Quantitative Methods", categoryZh: "数量方法", weight: "5–10%", title: "Regression coefficient", titleZh: "回归系数", explanation: "A slope coefficient estimates how the dependent variable changes when an independent variable rises by one unit, holding other included variables constant. Statistical significance is separate from economic importance.", explanationZh: "斜率系数估计某个自变量增加 1 单位时，因变量如何变化，同时保持模型内其他变量不变。统计显著不等于经济影响一定很大。", exampleZh: "例：销量对广告费的系数为 2，表示在其他条件相同下，广告费每增加 1 万元，预测销量增加 2 万件。", formula: "ŷ = b₀ + b₁x₁ + … + bₖxₖ" },
      { category: "Economics", categoryZh: "经济学", weight: "5–10%", title: "Interest-rate parity", titleZh: "利率平价", explanation: "Covered interest-rate parity links spot FX, forward FX, and two currency interest rates. Large deviations could otherwise permit a hedged arbitrage.", explanationZh: "抛补利率平价连接即期汇率、远期汇率和两种货币利率。若明显偏离，交易者可能通过借贷、投资和远期对冲实现套利。", exampleZh: "例：美元利率高于欧元利率时，欧元兑美元远期通常会相对即期作出调整，而不是免费多赚利差。", formula: "F = S × (1+rquote)/(1+rbase)" },
      { category: "Financial Statement Analysis", categoryZh: "财务报表分析", weight: "10–15%", title: "Equity method versus consolidation", titleZh: "权益法与合并报表", explanation: "Significant influence commonly leads to the equity method; control leads to consolidation. Classification changes reported revenue, assets, liabilities, and ratios even when underlying economics are similar.", explanationZh: "具有重大影响通常采用权益法，具有控制权则合并报表。即使经济利益相近，不同会计分类也会改变收入、资产、负债和财务比率。", exampleZh: "例：持有被投资公司 30% 且能参与决策，通常只确认自己份额的利润；控制子公司时则逐项合并其报表。", formula: "Influence → equity method | Control → consolidation" },
      { category: "Corporate Finance", categoryZh: "公司金融", weight: "5–10%", title: "Free cash flow to the firm", titleZh: "企业自由现金流 FCFF", explanation: "FCFF is cash available to all capital providers after operating expenses, taxes, and necessary investment. Discount it at WACC to estimate enterprise value.", explanationZh: "FCFF 是支付经营成本和税费并完成必要投资后，可供债权人与股东共同分配的现金。用 WACC 折现可估计企业价值。", exampleZh: "例：税后经营利润 100 元，加回折旧 20 元，资本开支 30 元、营运资本增加 10 元，则 FCFF = 80 元。", formula: "FCFF = NOPAT + D&A − Capex − ΔWC" },
      { category: "Equities", categoryZh: "权益投资", weight: "10–15%", title: "Enterprise value to equity value", titleZh: "从企业价值到股权价值", explanation: "Enterprise value reflects the operating business available to debt and equity investors. Subtract net debt and other senior claims, then add nonoperating assets to reach equity value.", explanationZh: "企业价值代表可供债权人和股东分享的经营业务价值。减去净债务和其他优先索偿、加回非经营资产，才得到股权价值。", exampleZh: "例：企业价值 1,000 万，债务 300 万、现金 50 万，则简化股权价值为 1,000−300+50 = 750 万。", formula: "Equity value = EV − debt + cash − other senior claims" },
      { category: "Fixed Income", categoryZh: "固定收益", weight: "10–15%", title: "Credit spread decomposition", titleZh: "信用利差拆解", explanation: "A corporate bond spread compensates for expected default loss, liquidity, risk premium, and other effects. Spread widening normally lowers the bond price even if government yields do not move.", explanationZh: "公司债利差补偿预期违约损失、流动性、风险溢价及其他因素。即使政府债收益率不变，信用利差扩大通常也会令公司债价格下跌。", exampleZh: "例：公司坏消息令其利差从 100bp 扩到 180bp；投资者要求更高收益率，旧债券价格因此下降。", formula: "Corporate yield ≈ benchmark yield + credit spread" },
      { category: "Derivatives and Risk Management", categoryZh: "衍生品与风险管理", weight: "5–10%", title: "Value a forward after inception", titleZh: "远期合约存续期估值", explanation: "A forward starts near zero value. Later, compare its contracted delivery price with the current forward price for the remaining maturity and discount the difference.", explanationZh: "远期合约建立时价值通常接近零。之后估值时，要比较合约交割价与相同剩余期限的当前远期价，再把差额折现。", exampleZh: "例：你锁定 100 元买入，当前同到期远期价为 108 元；这份低价买入权对多头具有正价值。", formula: "Long forward value ≈ PV(Fcurrent − K)" },
      { category: "Alternative Investments", categoryZh: "另类投资", weight: "5–10%", title: "Private-company valuation", titleZh: "非上市公司估值", explanation: "Private-company valuation often adjusts public-company multiples for size, liquidity, control, and company-specific risk. Reported prices are sparse, so assumptions matter greatly.", explanationZh: "非上市公司估值常以上市公司倍数为起点，再调整规模、流动性、控制权和公司特有风险。可观察交易少，因此假设影响很大。", exampleZh: "例：相似上市公司为 10× EBITDA，小型私人公司因更难出售而可能采用 8×，不能直接照搬 10×。", formula: "Private value ≈ adjusted comparable multiple × fundamental" },
      { category: "Portfolio Construction", categoryZh: "投资组合构建", weight: "10–15%", title: "Information ratio", titleZh: "信息比率", explanation: "The information ratio measures active return per unit of active risk. A manager needs both useful forecasts and disciplined portfolio construction to produce a strong ratio.", explanationZh: "信息比率衡量每承担一单位主动风险获得多少主动收益。优秀结果既需要有效预测，也需要有纪律的组合构建。", exampleZh: "例：组合跑赢基准 4%，跟踪误差 8%，信息比率为 0.5。另一经理跑赢 3% 但跟踪误差 3%，比率为 1.0。", formula: "IR = active return / tracking error" }
    ]
  },
  {
    id: "3",
    label: "Level III",
    labelZh: "三级 · 综合应用",
    focus: "Integrate and apply · 综合投资组合决策与书面论证",
    topics: [
      { category: "Ethical and Professional Standards", categoryZh: "道德与专业准则", weight: "10–15%", title: "Duty to clients in portfolio decisions", titleZh: "组合决策中的客户责任", explanation: "Recommendations must fit the client's objectives, constraints, and total portfolio. Fair dealing means giving clients a fair opportunity to act, not guaranteeing identical outcomes.", explanationZh: "建议必须适合客户目标、限制和整体组合。公平交易要求给客户公平行动机会，并不保证每个人获得完全相同结果。", exampleZh: "例：同一只高波动基金可能适合长期增长型客户，却不适合明年就要支付学费的客户。", formula: "Suitability = objectives + constraints + total portfolio" },
      { category: "Asset Allocation", categoryZh: "资产配置", weight: "15–20%", title: "Strategic versus tactical allocation", titleZh: "战略与战术资产配置", explanation: "Strategic allocation is the long-term policy mix consistent with goals and risk capacity. Tactical allocation makes temporary deviations when expected returns or risks differ from long-run assumptions.", explanationZh: "战略配置是符合目标和风险承受能力的长期政策组合；战术配置则在预期收益或风险偏离长期假设时，暂时偏离政策权重。", exampleZh: "例：长期政策为 60% 股票、40% 债券；经理暂时调到 55/45 是战术观点，不代表长期目标已经改变。", formula: "Actual allocation = strategic policy + tactical tilts" },
      { category: "Portfolio Construction", categoryZh: "投资组合构建", weight: "15–20%", title: "Risk budgeting", titleZh: "风险预算", explanation: "Risk budgeting allocates total portfolio risk across assets or strategies. Equal capital weights do not imply equal risk contributions because volatility and correlations differ.", explanationZh: "风险预算把组合总风险分配给不同资产或策略。由于波动率与相关性不同，资金权重相等并不代表风险贡献相等。", exampleZh: "例：股票和债券各投 50%，若股票波动远高于债券，组合风险可能几乎都来自股票。", formula: "Total risk = component risk contributions" },
      { category: "Performance Measurement", categoryZh: "业绩衡量", weight: "5–10%", title: "Return attribution", titleZh: "收益归因", explanation: "Attribution separates performance into allocation, security-selection, and interaction effects. Appraisal then asks whether results reflect skill, intended risk, or luck.", explanationZh: "收益归因把业绩拆为资产配置、证券选择和交互影响；业绩评价再判断结果来自能力、预期承担的风险还是运气。", exampleZh: "例：科技股整体上涨带来的收益属于配置效果；在科技板块内选中表现更好的公司属于选股效果。", formula: "Active return ≈ allocation + selection + interaction" },
      { category: "Derivatives and Risk Management", categoryZh: "衍生品与风险管理", weight: "10–15%", title: "Portfolio overlay", titleZh: "投资组合衍生品覆盖策略", explanation: "Futures, swaps, and options can alter beta, duration, currency exposure, or downside shape without trading every underlying holding. Basis, liquidity, counterparty, and roll risks remain.", explanationZh: "期货、掉期和期权可以在不逐项卖出持仓的情况下调整 Beta、久期、汇率敞口或下行风险形状，但仍有基差、流动性、对手方和展期风险。", exampleZh: "例：基金不卖出全部股票，而是卖股指期货，把组合 Beta 从 1.0 临时降到 0.7。", formula: "Required futures ≈ target exposure change / exposure per contract" },
      { category: "Portfolio Management Pathway", categoryZh: "投资组合管理方向", weight: "Pathway 30–35%", title: "Liability-driven investing", titleZh: "负债驱动投资 LDI", explanation: "LDI builds assets around the timing and interest-rate sensitivity of liabilities. Duration matching and cash-flow matching reduce funded-status risk rather than simply maximizing asset return.", explanationZh: "LDI 围绕负债的时间和利率敏感度配置资产。久期匹配与现金流匹配的目标是降低资金缺口风险，而不是单纯追求最高资产收益。", exampleZh: "例：养老基金十年后要支付一笔确定款项，可持有到期时间和久期接近的债券来降低利率变化影响。", formula: "Asset duration × asset value ≈ liability duration × liability value" },
      { category: "Private Markets Pathway", categoryZh: "私募市场方向", weight: "Pathway 30–35%", title: "Private equity waterfall", titleZh: "私募股权收益分配瀑布", explanation: "A waterfall determines how distributions are split between limited and general partners, commonly moving through return of capital, preferred return, catch-up, and carried interest.", explanationZh: "收益分配瀑布决定有限合伙人与普通合伙人如何分配现金，常依次经过返还本金、优先回报、追赶条款和业绩报酬。", exampleZh: "例：项目先把投资人的 100 元本金还清，再达到 8% 优先回报，之后管理人才能按约定分享超额收益。", formula: "Capital return → preferred return → catch-up → carry" },
      { category: "Private Wealth Pathway", categoryZh: "私人财富方向", weight: "Pathway 30–35%", title: "Goals-based wealth planning", titleZh: "目标导向财富规划", explanation: "Goals-based planning matches separate pools of assets to essential, important, and aspirational goals while considering taxes, liquidity, time horizon, and human capital.", explanationZh: "目标导向规划把不同资产池分别对应必要、重要和理想目标，同时考虑税务、流动性、期限和人力资本。", exampleZh: "例：两年后的学费放在低风险资产，二十年后的退休金可承担更多波动，梦想购艇资金则排在必要目标之后。", formula: "Fund essential goals before aspirational goals" }
    ]
  }
];

const cfaModuleOutlines = {
  "1": {
    "Ethical and Professional Standards": { weight: "15–20%", modules: ["Ethics and Trust in the Investment Profession", "Code of Ethics and Standards of Professional Conduct", "Guidance for Standards I–VII", "Introduction to the Global Investment Performance Standards (GIPS)", "Ethics Application"] },
    "Quantitative Methods": { weight: "6–9%", modules: ["Rates and Returns", "Time Value of Money in Finance", "Statistical Measures of Asset Returns", "Probability Trees and Conditional Expectations", "Portfolio Mathematics", "Simulation Methods", "Estimation and Inference", "Hypothesis Testing", "Parametric and Non-Parametric Tests of Independence", "Simple Linear Regression", "Introduction to Big Data Techniques"] },
    "Economics": { weight: "6–9%", modules: ["The Firm and Market Structures", "Understanding Business Cycles", "Fiscal Policy", "Monetary Policy", "Introduction to Geopolitics", "International Trade", "Capital Flows and the FX Market", "Exchange Rate Calculations"] },
    "Financial Statement Analysis": { weight: "11–14%", modules: ["Introduction to Financial Statement Analysis", "Analyzing Income Statements", "Analyzing Balance Sheets", "Analyzing Statements of Cash Flows I", "Analyzing Statements of Cash Flows II", "Analysis of Inventories", "Analysis of Long-Term Assets", "Topics in Long-Term Liabilities and Equity", "Analysis of Income Taxes", "Financial Reporting Quality", "Financial Analysis Techniques", "Introduction to Financial Statement Modeling"] },
    "Corporate Finance": { name: "Corporate Issuers", weight: "6–9%", modules: ["Organizational Forms, Corporate Issuer Features, and Ownership", "Investors and Other Stakeholders", "Corporate Governance: Conflicts, Mechanisms, Risks, and Benefits", "Working Capital and Liquidity", "Capital Investments and Capital Allocation", "Capital Structure", "Business Models"] },
    "Equities": { name: "Equity Investments", weight: "11–14%", modules: ["Market Organization and Structure", "Security Market Indexes", "Market Efficiency", "Overview of Equity Securities", "Company Analysis: Past and Present", "Industry and Competitive Analysis", "Company Analysis: Forecasting", "Equity Valuation: Concepts and Basic Tools"] },
    "Fixed Income": { weight: "11–14%", modules: ["Fixed-Income Instrument Features", "Fixed-Income Cash Flows and Types", "Fixed-Income Issuance and Trading", "Fixed-Income Markets for Corporate Issuers", "Fixed-Income Markets for Government Issuers", "Fixed-Income Bond Valuation: Prices and Yields", "Yield and Yield Spread Measures for Fixed-Rate Bonds", "Yield and Yield Spread Measures for Floating-Rate Instruments", "The Term Structure of Interest Rates: Spot, Par, and Forward Curves", "Interest Rate Risk and Return", "Yield-Based Bond Duration Measures and Properties", "Yield-Based Bond Convexity and Portfolio Properties", "Curve-Based and Empirical Fixed-Income Risk Measures", "Credit Risk", "Credit Analysis for Government Issuers", "Credit Analysis for Corporate Issuers", "Fixed-Income Securitization", "Asset-Backed Security (ABS) Instrument and Market Features", "Mortgage-Backed Security (MBS) Instrument and Market Features"] },
    "Derivatives and Risk Management": { name: "Derivatives", weight: "5–8%", modules: ["Derivative Instrument and Derivative Market Features", "Forward Commitment and Contingent Claim Features and Instruments", "Derivative Benefits, Risks, and Issuer and Investor Uses", "Arbitrage, Replication, and the Cost of Carry in Pricing Derivatives", "Pricing and Valuation of Forward Contracts and for an Underlying with Varying Maturities", "Pricing and Valuation of Futures Contracts", "Pricing and Valuation of Interest Rates and Other Swaps", "Pricing and Valuation of Options", "Option Replication Using Put–Call Parity", "Valuing a Derivative Using a One-Period Binomial Model"] },
    "Alternative Investments": { weight: "7–10%", modules: ["Alternative Investment Features, Methods, and Structures", "Alternative Investment Performance and Returns", "Investments in Private Capital: Equity and Debt", "Real Estate and Infrastructure", "Natural Resources", "Hedge Funds", "Introduction to Digital Assets"] },
    "Portfolio Construction": { name: "Portfolio Management", weight: "8–12%", modules: ["Portfolio Risk and Return: Part I", "Portfolio Risk and Return: Part II", "Portfolio Management: An Overview", "Basics of Portfolio Planning and Construction", "The Behavioral Biases of Individuals", "Introduction to Risk Management"] }
  },
  "2": {
    "Ethical and Professional Standards": { weight: "10–15%", modules: ["Code of Ethics and Standards of Professional Conduct", "Guidance for Standards I–VII", "Application of the Code and Standards: Level II"] },
    "Quantitative Methods": { weight: "5–10%", modules: ["Basics of Multiple Regression and Underlying Assumptions", "Evaluating Regression Model Fit and Interpreting Model Results", "Model Misspecification", "Extensions of Multiple Regression", "Time-Series Analysis", "Machine Learning", "Big Data Projects"] },
    "Economics": { weight: "5–10%", modules: ["Currency Exchange Rates: Understanding Equilibrium Value", "Economic Growth"] },
    "Financial Statement Analysis": { weight: "10–15%", modules: ["Intercorporate Investments", "Employee Compensation: Post-Employment and Share-Based", "Multinational Operations", "Analysis of Financial Institutions", "Evaluating Quality of Financial Reports", "Integration of Financial Statement Analysis Techniques"] },
    "Corporate Finance": { name: "Corporate Issuers", weight: "5–10%", modules: ["Analysis of Dividends and Share Repurchases", "Environmental, Social, and Governance (ESG) Considerations in Investment Analysis", "Cost of Capital: Advanced Topics", "Corporate Restructuring"] },
    "Equities": { name: "Equity Valuation", weight: "10–15%", modules: ["Equity Valuation: Applications and Processes", "Discounted Dividend Valuation", "Free Cash Flow Valuation", "Market-Based Valuation: Price and Enterprise Value Multiples", "Residual Income Valuation", "Private Company Valuation"] },
    "Fixed Income": { weight: "10–15%", modules: ["The Term Structure and Interest Rate Dynamics", "The Arbitrage-Free Valuation Framework", "Valuation and Analysis of Bonds with Embedded Options", "Credit Analysis Models", "Credit Default Swaps"] },
    "Derivatives and Risk Management": { name: "Derivatives", weight: "5–10%", modules: ["Pricing and Valuation of Forward Commitments", "Valuation of Contingent Claims"] },
    "Alternative Investments": { weight: "5–10%", modules: ["Introduction to Commodities and Commodity Derivatives", "Overview of Types of Real Estate Investment", "Investments in Real Estate through Publicly Traded Securities", "Hedge Fund Strategies"] },
    "Portfolio Construction": { name: "Portfolio Management", weight: "10–15%", modules: ["Economics and Investment Markets", "Analysis of Active Portfolio Management", "Exchange-Traded Funds: Mechanics and Applications", "Using Multifactor Models", "Measuring and Managing Market Risk", "Backtesting and Simulation"] }
  },
  "3": {
    "Ethical and Professional Standards": { weight: "10–15%", modules: ["Code of Ethics and Standards of Professional Conduct", "Guidance for Standards I–VII", "Application of the Code and Standards: Level III", "Asset Manager Code of Professional Conduct"] },
    "Asset Allocation": { weight: "15–20%", modules: ["Capital Market Expectations, Part 1: Framework and Macro Considerations", "Capital Market Expectations, Part 2: Forecasting Asset Class Returns", "Overview of Asset Allocation", "Principles of Asset Allocation", "Asset Allocation with Real-World Constraints"] },
    "Portfolio Construction": { weight: "15–20%", modules: ["Overview of Equity Portfolio Management", "Overview of Fixed-Income Portfolio Management", "Asset Allocation to Alternative Investments", "An Overview of Private Wealth Management", "Portfolio Management for Institutional Investors", "Trading Costs and Electronic Markets", "Case Study in Portfolio Management: Institutional (SWF)"] },
    "Performance Measurement": { weight: "5–10%", modules: ["Portfolio Performance Evaluation", "Investment Manager Selection", "Overview of the Global Investment Performance Standards"] },
    "Derivatives and Risk Management": { weight: "10–15%", modules: ["Options Strategies", "Swaps, Forwards, and Futures Strategies", "Currency Management: An Introduction"] },
    "Portfolio Management Pathway": { modules: ["Index-Based Equity Strategies", "Active Equity Investing: Strategies", "Active Equity Investing: Portfolio Construction", "Liability-Driven and Index-Based Strategies", "Yield Curve Strategies", "Fixed-Income Active Management: Credit Strategies", "Trade Strategy and Execution", "Case Study in Portfolio Management: Institutional (Endowment)"] },
    "Private Markets Pathway": { modules: ["Private Investments and Structures", "General Partner and Investor Perspectives and the Investment Process", "Private Equity", "Private Debt", "Private Special Situations", "Private Real Estate Investments", "Infrastructure"] },
    "Private Wealth Pathway": { modules: ["The Private Wealth Management Industry", "Working With the Wealthy", "Wealth Planning", "Investment Planning", "Preserving the Wealth", "Advising the Wealthy", "Transferring the Wealth"] }
  }
};

window.cfaReviewLevels.forEach(level => {
  level.topics.forEach(topic => {
    const outline = cfaModuleOutlines[level.id][topic.category];
    topic.officialCategory = outline.name || topic.category;
    topic.weight = outline.weight || topic.weight;
    topic.modules = outline.modules;
  });
  level.moduleCount = level.topics.reduce((total, topic) => total + topic.modules.length, 0);
});
